In [2]:
import tensorflow as tf
import numpy as np
import random

In [3]:
r=[0.15155207,0.11699013,0.26611059,0.15686263,0.00558321,0.2702405,0.03266088]
t = [0.13807413,0.12125762,0.13819417,0.15280597,0.16097994,0.1671388,0.12154939]

In [6]:
s=[ 0.08949357,  0.05534549,  0.22303611,  0.19108694, -0.15289583,
          0.15693004, -0.05748629]

In [7]:
np.array(r)-np.array(s)

array([ 0.0620585 ,  0.06164464,  0.04307448, -0.03422431,  0.15847904,
        0.11331046,  0.09014717])

In [5]:
r[0]-0.08949357


0.062058500000000016

In [9]:
a=[1.18152834, 1.03762603, 1.18255554, 1.30759164,0.,1.43024058, 1.04012275]
sum(a)

7.179664880000001

In [ ]:
(8.557202840661846,
  array([1.18152834, 1.03762603, 1.18255554, 1.30759164, 1.37753797,
         1.43024058, 1.04012275])),
 (array([0.13807413, 0.12125762, 0.13819417, 0.15280597, 0.16097994,
         0.1671388 , 0.12154939]),
  array([ 0.08949357,  0.05534549,  0.22303611,  0.19108694, -0.15289583,
          0.15693004, -0.05748629])),