In [6]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
print(tf.__version__)
print(np.__version__)

1.10.0
1.14.5


In [4]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
le.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1], dtype=int64)

In [7]:
data1 = pd.DataFrame(np.ones((6,3),dtype=float),columns = ['a','b','c'],index = pd.date_range('6/12/2012',periods =6))
data1

a    b    c
2012-06-12  1.0  1.0  1.0
2012-06-13  1.0  1.0  1.0
2012-06-14  1.0  1.0  1.0
2012-06-15  1.0  1.0  1.0
2012-06-16  1.0  1.0  1.0
2012-06-17  1.0  1.0  1.0

In [18]:
data2 = pd.DataFrame(np.ones((6,3),dtype = float) *2 ,columns=['b','a','c'],index=pd.date_range('6/13/2012',periods=6))
data2

b    a    c
2012-06-13  2.0  2.0  2.0
2012-06-14  2.0  2.0  2.0
2012-06-15  2.0  2.0  2.0
2012-06-16  2.0  2.0  2.0
2012-06-17  2.0  2.0  2.0
2012-06-18  2.0  2.0  2.0

In [19]:
q=data1.align(data2, join = 'outer', axis = 1)

In [22]:
q[1]

a    b    c
2012-06-13  2.0  2.0  2.0
2012-06-14  2.0  2.0  2.0
2012-06-15  2.0  2.0  2.0
2012-06-16  2.0  2.0  2.0
2012-06-17  2.0  2.0  2.0
2012-06-18  2.0  2.0  2.0

In [24]:
q0=data1.align(data2, join = 'outer')
q0

(              a    b    c
 2012-06-12  1.0  1.0  1.0
 2012-06-13  1.0  1.0  1.0
 2012-06-14  1.0  1.0  1.0
 2012-06-15  1.0  1.0  1.0
 2012-06-16  1.0  1.0  1.0
 2012-06-17  1.0  1.0  1.0
 2012-06-18  NaN  NaN  NaN,               a    b    c
 2012-06-12  NaN  NaN  NaN
 2012-06-13  2.0  2.0  2.0
 2012-06-14  2.0  2.0  2.0
 2012-06-15  2.0  2.0  2.0
 2012-06-16  2.0  2.0  2.0
 2012-06-17  2.0  2.0  2.0
 2012-06-18  2.0  2.0  2.0)

In [20]:
a=np.random.random_sample((5, 4,3))
b=np.random.random_sample((3,4))
a,b

(array([[[0.72194121, 0.79017054, 0.86031833],
         [0.45362227, 0.21484921, 0.30162813],
         [0.18022309, 0.53357689, 0.71158184],
         [0.20589694, 0.23404727, 0.95400504]],
 
        [[0.42156223, 0.46555517, 0.24740946],
         [0.3835823 , 0.57980794, 0.02064612],
         [0.50081878, 0.24821018, 0.78301602],
         [0.02058006, 0.89771353, 0.18332289]],
 
        [[0.08841863, 0.54556353, 0.98412263],
         [0.93626145, 0.41892589, 0.18994393],
         [0.25006613, 0.13401075, 0.30589425],
         [0.46299849, 0.66530692, 0.86282557]],
 
        [[0.75733338, 0.60369878, 0.62481236],
         [0.28300404, 0.28605406, 0.82601111],
         [0.63729697, 0.09342168, 0.81574122],
         [0.55042823, 0.54523028, 0.05529586]],
 
        [[0.31608318, 0.99562841, 0.66515355],
         [0.95731243, 0.98822307, 0.04665058],
         [0.05989905, 0.1102517 , 0.60199348],
         [0.17149861, 0.19073841, 0.15218979]]]),
 array([[0.2445579 , 0.78119912, 0.33276585, 

In [34]:
tmp = tf.slice(a,[0,0,0],[1,4,3])

TypeError: eval() arg 1 must be a string, bytes or code object

In [30]:
sess.run(tmp)

array([[[0.72194121, 0.79017054, 0.86031833],
        [0.45362227, 0.21484921, 0.30162813],
        [0.18022309, 0.53357689, 0.71158184],
        [0.20589694, 0.23404727, 0.95400504]]])

In [18]:
exp=tf.math.exp(a)
sess.run(exp)

array([[[2.12902691, 1.51273874, 1.29211305],
        [1.52766716, 1.51227445, 2.47967052],
        [1.43685147, 1.12833362, 1.2614625 ],
        [1.0388942 , 1.40440364, 1.38548623]],

       [[1.00253812, 1.28777261, 1.19391485],
        [1.15669072, 2.66055765, 1.48520092],
        [1.77046422, 1.28866792, 1.59826263],
        [1.83966184, 2.08089273, 2.50135096]],

       [[1.05637932, 1.12596527, 1.2669326 ],
        [1.55726087, 2.06437491, 1.0716313 ],
        [1.57129179, 2.65807111, 1.82350324],
        [1.15515215, 1.13093705, 1.04718554]],

       [[1.94080198, 1.0453783 , 2.48826932],
        [1.04335941, 2.32501358, 1.06085994],
        [1.70492864, 1.23750315, 1.48937698],
        [1.67378042, 1.32057431, 1.73002255]],

       [[2.49353611, 1.46416882, 2.04585582],
        [1.57144867, 1.53249379, 2.67788932],
        [2.55162284, 1.72113686, 1.23966231],
        [1.93730343, 1.58699135, 1.91997655]]])

In [16]:
sess.run(tmp)

array([[[0.75566503, 0.41392174],
        [0.42374184, 0.41361478],
        [0.36245424, 0.12074187],
        [0.03815688, 0.33961276]],

       [[0.00253491, 0.25291406],
        [0.1455631 , 0.97853574],
        [0.57124178, 0.25360906],
        [0.60958177, 0.732797  ]],

       [[0.05484733, 0.11864069],
        [0.44292842, 0.72482747],
        [0.45189808, 0.97760071],
        [0.14423207, 0.12304654]],

       [[0.66310128, 0.04437883],
        [0.04244571, 0.84372588],
        [0.53352326, 0.21309576],
        [0.5150848 , 0.27806672]],

       [[0.91370183, 0.38128772],
        [0.45199791, 0.42689633],
        [0.93672957, 0.54298504],
        [0.66129702, 0.46183999]]])

In [5]:
c= tf.matmul(a,b)
c

<tf.Tensor 'MatMul_1:0' shape=(5, 4, 4) dtype=float64>

In [9]:
tt=tf.where(tf.greater(a,0.5),a,tf.ones_like(a))

In [12]:
ttt=sess.run(tt)
ttt

array([[[1.        , 1.        , 0.50143813],
        [0.90873949, 1.        , 1.        ],
        [1.        , 1.        , 0.62797717],
        [0.65971669, 1.        , 0.99928964]],

       [[1.        , 1.        , 1.        ],
        [0.5157635 , 0.64838569, 1.        ],
        [0.80103591, 1.        , 1.        ],
        [1.        , 1.        , 1.        ]],

       [[0.75109417, 0.88812491, 0.89894051],
        [1.        , 0.74436146, 1.        ],
        [1.        , 1.        , 0.8755081 ],
        [0.61616766, 1.        , 1.        ]],

       [[1.        , 1.        , 0.8419214 ],
        [0.5876482 , 0.73067163, 1.        ],
        [0.52497206, 1.        , 1.        ],
        [0.68428641, 0.74041837, 0.592826  ]],

       [[1.        , 0.72408073, 1.        ],
        [0.87689976, 0.95821496, 1.        ],
        [1.        , 1.        , 0.87564624],
        [1.        , 1.        , 0.95154904]]])

In [13]:
ttt.shape

(5, 4, 3)

In [14]:
q=np.random.random_sample((5, 1,3))
p=np.random.random_sample((5, 3,7))
r=tf.matmul(q,p)
r

<tf.Tensor 'MatMul_2:0' shape=(5, 1, 7) dtype=float64>

In [4]:
a=np.random.random_sample((5, 4))
b=np.array([0,1,2,1])

In [5]:
e = tf.gather(a,b)

In [15]:
sess = tf.Session()

In [8]:
sess.run(e).shape

(4, 4)

In [73]:
a=np.random.random_sample((3, 4, 5))
a

array([[[0.28038546, 0.3422179 , 0.97020226, 0.18101137, 0.40244278],
        [0.77066657, 0.66387935, 0.55911901, 0.93298202, 0.47307378],
        [0.87257115, 0.64365955, 0.62498669, 0.1924089 , 0.65483317],
        [0.57492789, 0.61100102, 0.78549439, 0.34360318, 0.2347389 ]],

       [[0.04475713, 0.76181993, 0.79607498, 0.7643041 , 0.65394209],
        [0.44567791, 0.07423462, 0.32372991, 0.81176863, 0.55017833],
        [0.91311927, 0.54739744, 0.49768577, 0.54354578, 0.01405509],
        [0.71088362, 0.57188175, 0.14928459, 0.02185181, 0.50484779]],

       [[0.47559363, 0.14771258, 0.51536174, 0.72790559, 0.93575635],
        [0.7743118 , 0.54649694, 0.62714668, 0.25427172, 0.69193267],
        [0.87413603, 0.7406583 , 0.14127168, 0.9920868 , 0.41225779],
        [0.65783158, 0.94816413, 0.80868559, 0.75869396, 0.68550481]]])

In [74]:
x = tf.convert_to_tensor(a,dtype=tf.dtypes.float32)

In [76]:
# FM
summed_features_emb_square = tf.square(tf.reduce_sum(x,1))  # [bs,feature_num,emb_dim] -> [bs, emb_dim]
squared_sum_features_emb = tf.reduce_sum(tf.square(x),1)  # [bs,feature_num,emb_dim] -> [bs, emb_dim]
FM = 0.5 * tf.subtract(summed_features_emb_square, squared_sum_features_emb)  # [bs, emb_dim]

In [78]:
FM

<tf.Tensor 'mul_6:0' shape=(3, 5) dtype=float32>

In [80]:
# 22
embeddings = x
elementwise_list = []
for i in range(4):
    for j in range(i+1, 4):
        elementwise_list.append(tf.multiply(embeddings[:,i,:],embeddings[:,j,:]))  # (bs,emb_dim)
        
pairwise_interaction = tf.stack(elementwise_list)  # [feat_num * (feat_num - 1) / 2, bs, emb_dim]
pairwise_interaction = tf.transpose(pairwise_interaction, perm=[1,0,2])  # [bs, feat_num * (feat_num - 1) / 2, emb_dim]
pairwise_interaction = tf.reduce_sum(pairwise_interaction,1)

In [81]:
pairwise_interaction

<tf.Tensor 'Sum_4:0' shape=(3, 5) dtype=float32>

In [84]:
sess.run(FM)

array([[2.2391462, 1.8827784, 3.1904602, 0.8321066, 1.122935 ],
       [1.4655368, 1.3053784, 1.0564907, 1.523423 , 0.991702 ],
       [2.8581066, 1.9553864, 1.5227858, 2.6573532, 2.7169008]],
      dtype=float32)

In [85]:
sess.run(pairwise_interaction)

array([[2.239146  , 1.8827784 , 3.190461  , 0.8321065 , 1.122935  ],
       [1.4655367 , 1.3053784 , 1.0564907 , 1.5234232 , 0.99170196],
       [2.8581069 , 1.9553865 , 1.5227858 , 2.6573532 , 2.716901  ]],
      dtype=float32)

In [95]:
global_bias = tf.Variable(name='global_bias', initial_value=tf.zeros_initializer()(shape=[1]), dtype=tf.float32)
global_bias

<tf.Variable 'global_bias_2:0' shape=(1,) dtype=float32_ref>

In [98]:
tmp = tf.convert_to_tensor(np.random.random_sample((3, 1)),dtype=tf.dtypes.float32)
tmpp = tf.convert_to_tensor(np.random.random_sample((1,)),dtype=tf.dtypes.float32)
print(tmp,tmpp)
tmppp = tf.add_n([tmp,global_bias])
tmppp

Tensor("Const_19:0", shape=(3, 1), dtype=float32) Tensor("Const_20:0", shape=(1,), dtype=float32)


ValueError: Shapes must be equal rank, but are 2 and 1
	From merging shape 0 with other shapes. for 'AddN_4' (op: 'AddN') with input shapes: [3,1], [1].

In [48]:
w= tf.Variable(name='w',initial_value=tf.ones_initializer()(shape=[5]),dtype=tf.dtypes.float32)

In [49]:
ww= tf.Variable(name='ww',initial_value=tf.ones_initializer()(shape=[5,1]),dtype=tf.dtypes.float32)

In [50]:
xx = tf.reshape(x,[-1,1,5])

In [51]:
print(x,'\n',xx,'\n',w,'\n',ww)

Tensor("Const_1:0", shape=(4, 5), dtype=float32) 
 Tensor("Reshape_2:0", shape=(4, 1, 5), dtype=float32) 
 <tf.Variable 'w:0' shape=(5,) dtype=float32_ref> 
 <tf.Variable 'ww:0' shape=(5, 1) dtype=float32_ref>


In [91]:
sess.run(tf.initialize_all_variables())

In [56]:
xb = tf.tensordot(xx,w,1)
xb

<tf.Tensor 'Tensordot_6:0' shape=(4, 1) dtype=float32>

In [57]:
sess.run(xb)

array([[1.2667975],
       [2.050785 ],
       [2.5211918],
       [1.9150916]], dtype=float32)

In [45]:
inner = tf.matmul(x,ww)
inner

<tf.Tensor 'MatMul_4:0' shape=(4, 1) dtype=float32>

In [43]:
sess.run(inner)

array([[1.2667975],
       [2.050785 ],
       [2.5211918],
       [1.9150916]], dtype=float32)

In [66]:
c1 = x * xb
c1

<tf.Tensor 'mul_4:0' shape=(4, 5) dtype=float32>

In [67]:
c2 = x * inner
c2

<tf.Tensor 'mul_5:0' shape=(4, 5) dtype=float32>

In [68]:
sess.run(c1)

array([[0.16764057, 0.35058174, 0.00817578, 0.78767204, 0.290706  ],
       [0.8395495 , 0.6565793 , 0.45572087, 1.1918169 , 1.0620527 ],
       [1.675561  , 0.9217841 , 0.5853849 , 1.2105631 , 1.963115  ],
       [0.46725735, 1.3554226 , 0.7629892 , 0.16831522, 0.9135916 ]],
      dtype=float32)

In [69]:
sess.run(c2)

array([[0.16764057, 0.35058174, 0.00817578, 0.78767204, 0.290706  ],
       [0.8395495 , 0.6565793 , 0.45572087, 1.1918169 , 1.0620527 ],
       [1.675561  , 0.9217841 , 0.5853849 , 1.2105631 , 1.963115  ],
       [0.46725735, 1.3554226 , 0.7629892 , 0.16831522, 0.9135916 ]],
      dtype=float32)

In [4]:
asoft=tf.nn.softmax(a)

In [9]:
sess = tf.Session()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


TypeError: target must be a string, but got <class 'tensorflow.python.framework.ops.Operation'>

In [6]:
ase=sess.run(asoft)
ase

array([[0.27002291, 0.1556176 , 0.17645783, 0.12424852, 0.27365314],
       [0.13586864, 0.18513274, 0.20827623, 0.14871279, 0.3220096 ],
       [0.11694078, 0.13309307, 0.23243326, 0.22412005, 0.29341284],
       [0.26712924, 0.19731266, 0.13249412, 0.17239785, 0.23066613]])

In [7]:
asig=tf.nn.sigmoid(a)

In [8]:
asi=sess.run(asig)
asi

array([[0.7125883 , 0.5882857 , 0.61835296, 0.5328937 , 0.71531562],
       [0.51555772, 0.59185412, 0.61997159, 0.538071  , 0.71608903],
       [0.51247189, 0.54470007, 0.67630302, 0.66827914, 0.7250818 ],
       [0.72945809, 0.66572928, 0.57216275, 0.63505088, 0.69954112]])

In [9]:
asp=tf.nn.softplus(a)

In [10]:
asp=sess.run(asp)
asp

array([[1.24683959, 0.88742561, 0.96325909, 0.76119841, 1.25637415],
       [0.72475699, 0.89613062, 0.96750928, 0.77234408, 1.25909456],
       [0.71840733, 0.78679889, 1.12794745, 1.10346145, 1.2912817 ],
       [1.30732826, 1.09580408, 0.84901241, 1.00799733, 1.20244436]])

In [19]:
sum(ase[1])

0.9999999999999999

In [18]:
sum(ase[:,1])

0.5748890951710182

In [4]:
import tensorflow.keras as keras

class SimpleMLP(keras.Model):

    def __init__(self, use_bn=True, use_dp=True, num_classes=10):
        super(SimpleMLP, self).__init__(name='mlp')
        self.use_bn = use_bn
        self.use_dp = use_dp
        self.num_classes = num_classes

        self.dense1 = keras.layers.Dense(32, activation='relu')
        self.dense2 = keras.layers.Dense(num_classes, activation='softmax')
        if self.use_dp:
            self.dp = keras.layers.Dropout(0.5)
        if self.use_bn:
            self.bn = keras.layers.BatchNormalization(axis=-1)

    def call(self, inputs):
        x = self.dense1(inputs)
        if self.use_dp:
            x = self.dp(x)
        if self.use_bn:
            x = self.bn(x)
        return self.dense2(x)

model = SimpleMLP()

In [5]:
model.updates

[]

In [8]:
tf.get_collection(tf.GraphKeys.UPDATE_OPS)

[]

In [9]:
isinstance(model,tf.keras.layers.Layer)

True