In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)
print(np.__version__)

1.15.0
1.19.0


In [3]:
a=np.random.random_sample((4, 5))
a

array([[0.90798814, 0.35688305, 0.48256325, 0.13176509, 0.92134274],
       [0.06225098, 0.37163553, 0.48942766, 0.15257932, 0.92514378],
       [0.04989791, 0.17927893, 0.73683341, 0.70041213, 0.9698109 ],
       [0.9918749 , 0.6889319 , 0.29068061, 0.55394718, 0.84511366]])

In [4]:
asoft=tf.nn.softmax(a)

In [5]:
sess = tf.Session()

In [6]:
ase=sess.run(asoft)
ase

array([[0.27002291, 0.1556176 , 0.17645783, 0.12424852, 0.27365314],
       [0.13586864, 0.18513274, 0.20827623, 0.14871279, 0.3220096 ],
       [0.11694078, 0.13309307, 0.23243326, 0.22412005, 0.29341284],
       [0.26712924, 0.19731266, 0.13249412, 0.17239785, 0.23066613]])

In [7]:
asig=tf.nn.sigmoid(a)

In [8]:
asi=sess.run(asig)
asi

array([[0.7125883 , 0.5882857 , 0.61835296, 0.5328937 , 0.71531562],
       [0.51555772, 0.59185412, 0.61997159, 0.538071  , 0.71608903],
       [0.51247189, 0.54470007, 0.67630302, 0.66827914, 0.7250818 ],
       [0.72945809, 0.66572928, 0.57216275, 0.63505088, 0.69954112]])

In [9]:
asp=tf.nn.softplus(a)

In [10]:
asp=sess.run(asp)
asp

array([[1.24683959, 0.88742561, 0.96325909, 0.76119841, 1.25637415],
       [0.72475699, 0.89613062, 0.96750928, 0.77234408, 1.25909456],
       [0.71840733, 0.78679889, 1.12794745, 1.10346145, 1.2912817 ],
       [1.30732826, 1.09580408, 0.84901241, 1.00799733, 1.20244436]])

In [19]:
sum(ase[1])

0.9999999999999999

In [18]:
sum(ase[:,1])

0.5748890951710182

In [4]:
import tensorflow.keras as keras

class SimpleMLP(keras.Model):

    def __init__(self, use_bn=True, use_dp=True, num_classes=10):
        super(SimpleMLP, self).__init__(name='mlp')
        self.use_bn = use_bn
        self.use_dp = use_dp
        self.num_classes = num_classes

        self.dense1 = keras.layers.Dense(32, activation='relu')
        self.dense2 = keras.layers.Dense(num_classes, activation='softmax')
        if self.use_dp:
            self.dp = keras.layers.Dropout(0.5)
        if self.use_bn:
            self.bn = keras.layers.BatchNormalization(axis=-1)

    def call(self, inputs):
        x = self.dense1(inputs)
        if self.use_dp:
            x = self.dp(x)
        if self.use_bn:
            x = self.bn(x)
        return self.dense2(x)

model = SimpleMLP()

In [5]:
model.updates

[]

In [8]:
tf.get_collection(tf.GraphKeys.UPDATE_OPS)

[]

In [9]:
isinstance(model,tf.keras.layers.Layer)

True