In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [10]:
a=tf.glorot_normal_initializer(seed=1)([3,4])

In [4]:
sess = tf.Session()

In [10]:
sess.run(tf.global_variables_initializer())

In [6]:
sess.run(a)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [8]:
b=tf.zeros_initializer()([3,4])

In [9]:
sess.run(b)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [17]:
c=tf.cast(tf.initializers.he_normal(seed=1)(shape=[3,4]),tf.float16)

In [18]:
sess.run(c)

array([[-0.753   ,  1.378   ,  0.06064 ,  0.0921  ],
       [ 0.5938  ,  1.495   ,  0.1519  , -1.407   ],
       [ 1.262   ,  0.503   , -0.7983  , -0.003736]], dtype=float16)

In [20]:
d=tf.keras.initializers.GlorotNormal(
    seed=1
)

AttributeError: module 'tensorflow.python.keras.api._v1.keras.initializers' has no attribute 'GlorotNormal'

In [21]:
w=[1,2,3]
w[4]

IndexError: list index out of range

In [22]:
if w[4]:
    print('d')

IndexError: list index out of range

In [9]:
a= tf.Variable(name='ba',initial_value=tf.zeros_initializer()(shape=[2,3]), dtype=tf.float32)
b= tf.Variable(name='bb',initial_value=tf.ones_initializer()(shape=[1]), dtype=tf.float32)
c=tf.add(a,b)

In [11]:
sess.run(c)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [14]:
sess.run(a)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [15]:
help(hash)

Help on built-in function hash in module builtins:

hash(obj, /)
    Return the hash value for the given object.
    
    Two objects that compare equal must also have the same hash value, but the
    reverse is not necessarily true.

